### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] Create a data model which shows which way the car is facing
- [ ] Listen for a keydown events on the keydown
- [ ] Use WASD to determine what direction the car is facing
