### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] Keep track where the car by adding a location to your data-model, to hold your car's coordinates ( x and y). 
- [ ] Use absolute positioning, and utilize the style method of element objects to change your cars top and left box offset styles
- [ ] for keydown events, keep track if the user hits space.
- [ ] If the user hits space, activate a timer that runs 16ms, and move the car a few pixels.
