### ISSUE TITLE
Issue 4 Users can stop their car

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [ ] Add a boolean to your data model to indicate whether or not the car is started.
- [ ] If it has started and the user has clicked space again, stop the vehicle at its position
- [ ] Make any modifications to your previous document if needed to ensure full functionality
